project_id = "uszvrhpcmtmpxlcgfhjp"

[functions.create-virtual-account]
verify_jwt = false

[functions.paymentpoint-webhook]
verify_jwt = false

[functions.rgc-services]
verify_jwt = false

[functions.withdraw-cashback]
verify_jwt = false

[functions.isquare-services]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false
